---
- hosts: all
  become: true
  tasks:
	- name: "Ansible | Print a variable"
		debug:
			msg: "The operating system is {{ ansible_distribution }}"
    - debug:
        msg: "Yeah!"

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600      
    
    - name: Install libraries
      apt:
        name: "{{ item }}"        
        force_apt_get: true
      with_items: 
        - mysql-server
        - python-pymysql
        - python3-pymysql
        - python-apt
        - python3-apt

    - name: Add databases
      mysql_db:
        name: "{{ item }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      with_items:
        - first
        - second  

    - name: Install nginx
      apt:
        name: nginx

    - name: Copy index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html

